'use client'
import { FormEvent, useEffect, useState } from 'react'

type Tenant = { id: string; domain: string; databaseName: string; isActive: boolean; updatedAt?: string }
type Admin = { id: string; email: string; fullName: string; isActive: boolean; createdAt?: string }
type Dashboard = { totalTenants: number; activeTenants: number; inactiveTenants: number; activeAdmins: number; latestTenants: Array<Pick<Tenant, 'id' | 'domain' | 'isActive' | 'updatedAt'>> }
type Screen = 'dashboard' | 'tenants' | 'admins' | 'detail'
const request = async (path: string, token?: string, init?: RequestInit) => fetch(`/api${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...init?.headers } })

export default function Home() {
  const [token, setToken] = useState<string | null>(null), [screen, setScreen] = useState<Screen>('dashboard'), [tenants, setTenants] = useState<Tenant[]>([]), [admins, setAdmins] = useState<Admin[]>([]), [dashboard, setDashboard] = useState<Dashboard | null>(null), [selected, setSelected] = useState<Tenant | null>(null), [editing, setEditing] = useState<Tenant | null>(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [monitor, setMonitor] = useState<{ status: string; latencyMs: number } | null>(null), [tenantSaving, setTenantSaving] = useState(false), [seedLoading, setSeedLoading] = useState(false), [routeTenantId, setRouteTenantId] = useState<string | null>(null)
  const call = async (path: string, init?: RequestInit) => { const res = await request(path, token || undefined, init); if (res.status === 401) { localStorage.removeItem('tenant-console-token'); setToken(null); throw new Error('Phiên đăng nhập đã hết hạn') } const data = await res.json(); if (!res.ok) throw new Error(data.message || 'Không thể thực hiện yêu cầu'); return data }
  const loadAll = async (activeToken = token) => { if (!activeToken) return; try { const load = async (path: string) => { const response = await request(path, activeToken); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Không thể tải dữ liệu'); return data }; const [dashboardData, tenantData, adminData] = await Promise.all([load('/dashboard'), load('/tenants'), load('/admins')]); setDashboard(dashboardData.data); setTenants(tenantData.data); setAdmins(adminData.data) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tải dữ liệu') } }
  const syncRouteFromUrl = () => {
    const params = new URLSearchParams(window.location.search)
    const nextScreen = params.get('screen')
    setScreen(nextScreen === 'tenants' || nextScreen === 'admins' || nextScreen === 'detail' ? nextScreen : 'dashboard')
    setRouteTenantId(params.get('tenantId'))
  }
  const navigate = (nextScreen: Screen, tenantId?: string) => {
    const url = new URL(window.location.href)
    if (nextScreen === 'dashboard') url.searchParams.delete('screen')
    else url.searchParams.set('screen', nextScreen)
    if (tenantId) url.searchParams.set('tenantId', tenantId)
    else url.searchParams.delete('tenantId')
    window.history.pushState({}, '', url)
    setScreen(nextScreen)
    setRouteTenantId(tenantId || null)
  }
  useEffect(() => { const stored = localStorage.getItem('tenant-console-token'); setToken(stored); syncRouteFromUrl(); window.addEventListener('popstate', syncRouteFromUrl); if (stored) void loadAll(stored); return () => window.removeEventListener('popstate', syncRouteFromUrl) }, [])
  useEffect(() => { if (screen !== 'detail' || !routeTenantId || selected?.id === routeTenantId) return; const tenant = tenants.find((item) => item.id === routeTenantId); if (tenant) void openDetail(tenant, false) }, [screen, routeTenantId, tenants, selected?.id])
  const login = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); const fd = new FormData(event.currentTarget); const res = await request('/auth/login', undefined, { method: 'POST', body: JSON.stringify({ email: fd.get('email'), password: fd.get('password') }) }); const data = await res.json(); if (!res.ok) { setError(data.message || 'Thông tin đăng nhập không đúng'); return } localStorage.setItem('tenant-console-token', data.accessToken); setToken(data.accessToken); setTimeout(() => void loadAll(), 0) }
  const saveTenant = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); setError(''); setTenantSaving(true); try { const cloneFromTenantId = fd.get('cloneFromTenantId'); await call(editing ? `/tenants/${editing.id}` : '/tenants', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify({ domain: fd.get('domain'), databaseName: fd.get('databaseName'), cloneFromTenantId: cloneFromTenantId || undefined, isActive: fd.get('isActive') === 'on' }) }); setNotice(cloneFromTenantId ? 'Đã clone tenant mẫu và tạo tenant mới' : 'Đã lưu tenant và khởi tạo database'); setEditing(null); await loadAll() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể lưu tenant') } finally { setTenantSaving(false) } }
  const saveAdmin = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); try { await call('/admins', { method: 'POST', body: JSON.stringify({ fullName: fd.get('fullName'), email: fd.get('email'), password: fd.get('password') }) }); setNotice('Đã tạo Super Admin'); event.currentTarget.reset(); await loadAll() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tạo Super Admin') } }
  const openDetail = async (tenant: Tenant, updateUrl = true) => { setSelected(tenant); if (updateUrl) navigate('detail', tenant.id); else setScreen('detail'); setMonitor(null); try { const data = await call(`/tenants/${tenant.id}/monitor`); setMonitor(data.data.database) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể kiểm tra tenant') } }
  const runSeed = async (tenant: Tenant) => {
    if (!window.confirm(`Chạy lại seed dữ liệu mặc định cho ${tenant.domain}? Các dữ liệu đã có sẽ được giữ nguyên.`)) return
    setError('')
    setSeedLoading(true)
    try {
      await call(`/tenants/${tenant.id}/seed`, { method: 'POST' })
      setNotice(`Đã chạy seed cho ${tenant.domain}`)
      await openDetail(tenant)
    } catch (e) { setError(e instanceof Error ? e.message : 'Không thể chạy seed tenant') } finally { setSeedLoading(false) }
  }
  const toggleAdmin = async (admin: Admin) => { try { await call(`/admins/${admin.id}`, { method: 'PATCH', body: JSON.stringify({ isActive: !admin.isActive }) }); setNotice('Đã cập nhật Super Admin'); await loadAll() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật Super Admin') } }
  if (!token) return <main className="login"><form onSubmit={login}><h1>Tenant Console</h1><p>Đăng nhập Super Admin</p><label>Email<input name="email" type="email" defaultValue="superadmin@vienvu.com" required /></label><label>Mật khẩu<input name="password" type="password" defaultValue="dhusagfydastfydsayfdtyasfd2314321432" required /></label>{error && <span className="error">{error}</span>}<button className="primary">Đăng nhập</button></form></main>
  const nav = (key: Screen, label: string) => <button className={screen === key ? 'nav-active' : ''} onClick={() => navigate(key)}>{label}</button>
  return <main className="console"><aside><div className="brand">TENANT<br /><strong>CONSOLE</strong></div><nav>{nav('dashboard', 'Tổng quan')}{nav('tenants', 'Tenant')}{nav('admins', 'Super Admin')}</nav><button className="logout" onClick={() => { localStorage.removeItem('tenant-console-token'); setToken(null) }}>Đăng xuất</button></aside><section className="content">{error && <p className="message error">{error}</p>}{notice && <p className="message success">{notice}</p>}
    {screen === 'dashboard' && <><header><div><h1>Tổng quan nền tảng</h1><p>Trạng thái quản lý các hệ thống tenant.</p></div><button onClick={() => void loadAll()}>Làm mới</button></header><div className="metrics"><Metric label="Tổng tenant" value={dashboard?.totalTenants ?? '—'} /><Metric label="Đang hoạt động" value={dashboard?.activeTenants ?? '—'} good /><Metric label="Tạm dừng" value={dashboard?.inactiveTenants ?? '—'} /><Metric label="Super Admin" value={dashboard?.activeAdmins ?? '—'} /></div><section className="card"><h2>Tenant cập nhật gần đây</h2><TenantTable rows={dashboard?.latestTenants || []} onDetail={(id) => { const tenant = tenants.find((item) => item.id === id); if (tenant) void openDetail(tenant) }} /></section></>}
    {screen === 'tenants' && <><header><div><h1>Quản lý tenant</h1><p>Nhập tên database; hệ thống tự tạo database trên server MySQL dùng chung.</p></div><button className="primary" onClick={() => setEditing({ id: '', domain: '', databaseName: '', isActive: true })}>Thêm tenant</button></header>{editing && <section className="card"><h2>{editing.id ? 'Cập nhật tenant' : 'Thêm tenant'}</h2><form className="form-grid" onSubmit={saveTenant}><fieldset disabled={tenantSaving}><label>Domain<input name="domain" defaultValue={editing.domain} required placeholder="clinic-a.example.com" /></label><label>Tên database<input name="databaseName" defaultValue={editing.databaseName.replace(/^clinic_/i, '')} required placeholder="a" pattern="[A-Za-z0-9_-]{1,57}" /><small>Hệ thống tự thêm prefix <code>clinic_</code> và tạo database, ví dụ: <code>clinic_a</code>.</small></label>{!editing.id && <label>Clone từ tenant mẫu<select name="cloneFromTenantId" defaultValue=""><option value="">Không clone — tạo dữ liệu mặc định</option>{tenants.filter((tenant) => tenant.isActive).map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.domain} ({tenant.databaseName})</option>)}</select><small>Clone sao chép toàn bộ bảng và dữ liệu từ tenant mẫu vào database mới.</small></label>}<label className="check"><input name="isActive" type="checkbox" defaultChecked={editing.isActive} /> Đang hoạt động</label><div className="form-actions"><button className="primary">{tenantSaving ? 'Đang tạo / sao chép dữ liệu…' : 'Lưu tenant'}</button><button type="button" onClick={() => setEditing(null)}>Huỷ</button></div></fieldset>{tenantSaving && <p className="form-progress">Đang tạo database và đồng bộ dữ liệu. Không đóng trang này.</p>}</form></section>}<section className="card"><TenantTable rows={tenants} onDetail={(id) => { const tenant = tenants.find((item) => item.id === id); if (tenant) void openDetail(tenant) }} onEdit={(id) => setEditing(tenants.find((item) => item.id === id) || null)} /></section></>}
    {screen === 'admins' && <><header><div><h1>Quản lý Super Admin</h1><p>Tài khoản quản trị management database, tách biệt hoàn toàn tenant.</p></div></header><div className="two-column"><section className="card"><h2>Thêm Super Admin</h2><form className="form-grid" onSubmit={saveAdmin}><label>Họ tên<input name="fullName" required /></label><label>Email<input name="email" type="email" required /></label><label>Mật khẩu<input name="password" type="password" minLength={12} required /></label><button className="primary">Tạo tài khoản</button></form></section><section className="card"><h2>Danh sách tài khoản</h2>{admins.map((admin) => <div className="admin-row" key={admin.id}><span><strong>{admin.fullName}</strong><small>{admin.email}</small></span><span><span className={admin.isActive ? 'badge good' : 'badge'}>{admin.isActive ? 'Hoạt động' : 'Tạm dừng'}</span><button onClick={() => void toggleAdmin(admin)}>{admin.isActive ? 'Tạm dừng' : 'Kích hoạt'}</button></span></div>)}</section></div></>}
    {screen === 'detail' && !selected && <p className="message loading">Đang tải thông tin tenant…</p>}
    {screen === 'detail' && selected && <><header><div><button onClick={() => navigate('tenants')}>← Tenant</button><h1>{selected.domain}</h1><p>Trang chi tiết và giám sát tenant.</p></div><div><button className="primary" disabled={!selected.isActive || seedLoading} onClick={() => void runSeed(selected)}>{seedLoading ? 'Đang chạy seed…' : 'Run seed'}</button><button disabled={seedLoading} onClick={() => void openDetail(selected, false)}>Kiểm tra lại</button></div></header>{seedLoading && <p className="message loading">Đang khởi tạo dữ liệu mặc định cho tenant. Vui lòng chờ.</p>}<div className="metrics"><Metric label="Trạng thái tenant" value={selected.isActive ? 'Hoạt động' : 'Tạm dừng'} good={selected.isActive} /><Metric label="Database" value={monitor?.status === 'healthy' ? 'Kết nối tốt' : monitor?.status === 'unreachable' ? 'Không kết nối' : 'Đang kiểm tra'} good={monitor?.status === 'healthy'} /><Metric label="Độ trễ DB" value={monitor ? `${monitor.latencyMs} ms` : '—'} /></div><section className="card detail-grid"><div><span>Domain</span><strong>{selected.domain}</strong></div><div><span>Tên database</span><strong>{selected.databaseName}</strong></div><div><span>Đồng bộ gần nhất</span><strong>{selected.updatedAt ? new Date(selected.updatedAt).toLocaleString('vi-VN') : '—'}</strong></div></section></>}
  </section></main>
}
function Metric({ label, value, good }: { label: string; value: string | number; good?: boolean }) { return <div className="metric"><span>{label}</span><strong className={good ? 'good-text' : ''}>{value}</strong></div> }
function TenantTable({ rows, onDetail, onEdit }: { rows: Array<Pick<Tenant, 'id' | 'domain' | 'isActive' | 'updatedAt'>>; onDetail: (id: string) => void; onEdit?: (id: string) => void }) { return <table><thead><tr><th>Domain</th><th>Trạng thái</th><th>Cập nhật</th><th /></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><button className="link" onClick={() => onDetail(item.id)}>{item.domain}</button></td><td><span className={item.isActive ? 'badge good' : 'badge'}>{item.isActive ? 'Hoạt động' : 'Tạm dừng'}</span></td><td>{item.updatedAt ? new Date(item.updatedAt).toLocaleDateString('vi-VN') : '—'}</td><td>{onEdit && <button onClick={() => onEdit(item.id)}>Sửa</button>}</td></tr>)}</tbody></table> }
