'use client'
import { FormEvent, useEffect, useState } from 'react'
import { usePathname, useRouter } from 'next/navigation'

type Tenant = { id: string; domain: string; databaseName: string; isActive: boolean; databaseSummary?: DatabaseSummary | null; databaseSummarySyncedAt?: string | null; updatedAt?: string }
type Admin = { id: string; email: string; fullName: string; isActive: boolean; createdAt?: string }
type Dashboard = { totalTenants: number; activeTenants: number; inactiveTenants: number; activeAdmins: number; latestTenants: Array<Pick<Tenant, 'id' | 'domain' | 'isActive' | 'updatedAt'>> }
type DatabaseSummary = { databaseName: string; engine: string; version: string; totalTables: number; estimatedRows: number; sizeBytes: number; largestTables: Array<{ name: string; rows: number; sizeBytes: number }> }
type Screen = 'dashboard' | 'tenants' | 'admins' | 'detail'
const request = async (path: string, init?: RequestInit) => fetch(`/api${path}`, { ...init, credentials: 'same-origin', headers: { 'Content-Type': 'application/json', ...init?.headers } })

export default function Home() {
  const pathname = usePathname()
  const router = useRouter()
  const [token, setToken] = useState<string | null>(null), [screen, setScreen] = useState<Screen>('dashboard'), [tenants, setTenants] = useState<Tenant[]>([]), [admins, setAdmins] = useState<Admin[]>([]), [dashboard, setDashboard] = useState<Dashboard | null>(null), [selected, setSelected] = useState<Tenant | null>(null), [editing, setEditing] = useState<Tenant | null>(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [monitor, setMonitor] = useState<{ status: string; latencyMs: number } | null>(null), [databaseSummary, setDatabaseSummary] = useState<DatabaseSummary | null>(null), [tenantSaving, setTenantSaving] = useState(false), [seedLoading, setSeedLoading] = useState(false), [summaryLoading, setSummaryLoading] = useState(false), [allSummariesLoading, setAllSummariesLoading] = useState(false), [routeTenantId, setRouteTenantId] = useState<string | null>(null)
  const call = async (path: string, init?: RequestInit) => { const res = await request(path, init); if (res.status === 401) { setToken(null); throw new Error('Phiên đăng nhập đã hết hạn') } const data = await res.json(); if (!res.ok) throw new Error(data.message || 'Không thể thực hiện yêu cầu'); return data }
  const loadAll = async (authenticated = token) => { if (!authenticated) return; try { const load = async (path: string) => { const response = await request(path); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Không thể tải dữ liệu'); return data }; const [dashboardData, tenantData, adminData] = await Promise.all([load('/dashboard'), load('/tenants'), load('/admins')]); setDashboard(dashboardData.data); setTenants(tenantData.data); setAdmins(adminData.data) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tải dữ liệu') } }
  const syncRouteFromUrl = () => {
    const segments = window.location.pathname.split('/').filter(Boolean)
    if (segments[0] === 'admins') { setScreen('admins'); setRouteTenantId(null); return }
    if (segments[0] === 'tenants' && segments[1]) { setScreen('detail'); setRouteTenantId(segments[1]); return }
    if (segments[0] === 'tenants') { setScreen('tenants'); setRouteTenantId(null); return }
    setScreen('dashboard'); setRouteTenantId(null)
  }
  const navigate = (nextScreen: Screen, tenantId?: string) => {
    const target = nextScreen === 'admins' ? '/admins' : nextScreen === 'tenants' ? '/tenants' : nextScreen === 'detail' && tenantId ? `/tenants/${tenantId}` : '/'
    router.push(target)
    setScreen(nextScreen)
    setRouteTenantId(tenantId || null)
  }
  useEffect(() => { syncRouteFromUrl() }, [pathname])
  useEffect(() => { void request('/auth/me').then((response) => { if (!response.ok) return; setToken('session'); void loadAll('session') }) }, [])
  useEffect(() => { if (screen !== 'detail' || !routeTenantId || selected?.id === routeTenantId) return; const tenant = tenants.find((item) => item.id === routeTenantId); if (tenant) void openDetail(tenant, false) }, [screen, routeTenantId, tenants, selected?.id])
  const login = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); const fd = new FormData(event.currentTarget); const res = await request('/auth/login', { method: 'POST', body: JSON.stringify({ email: fd.get('email'), password: fd.get('password') }) }); const data = await res.json(); if (!res.ok) { setError(data.message || 'Thông tin đăng nhập không đúng'); return } setToken('session'); await loadAll('session'); const next = new URLSearchParams(window.location.search).get('next'); router.replace(next && next.startsWith('/') ? next : '/') }
  const saveTenant = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); setError(''); setTenantSaving(true); try { const cloneFromTenantId = fd.get('cloneFromTenantId'); await call(editing ? `/tenants/${editing.id}` : '/tenants', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify({ domain: fd.get('domain'), databaseName: fd.get('databaseName'), cloneFromTenantId: cloneFromTenantId || undefined, isActive: fd.get('isActive') === 'on' }) }); setNotice(cloneFromTenantId ? 'Đã clone tenant mẫu và tạo tenant mới' : 'Đã lưu tenant và khởi tạo database'); setEditing(null); await loadAll() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể lưu tenant') } finally { setTenantSaving(false) } }
  const saveAdmin = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); try { await call('/admins', { method: 'POST', body: JSON.stringify({ fullName: fd.get('fullName'), email: fd.get('email'), password: fd.get('password') }) }); setNotice('Đã tạo Super Admin'); event.currentTarget.reset(); await loadAll() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tạo Super Admin') } }
  const openDetail = async (tenant: Tenant, updateUrl = true) => { setSelected(tenant); if (updateUrl) navigate('detail', tenant.id); else setScreen('detail'); setMonitor(null); setDatabaseSummary(tenant.databaseSummary || null); try { const data = await call(`/tenants/${tenant.id}/monitor`); setMonitor(data.data.database); setDatabaseSummary(data.data.summary || null); await syncDatabaseSummary(tenant, true) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể kiểm tra tenant') } }
  const syncDatabaseSummary = async (tenant: Tenant, silent = false) => { setError(''); setSummaryLoading(true); try { const data = await call(`/tenants/${tenant.id}/monitor`, { method: 'POST' }); const next = { ...tenant, databaseSummary: data.data.summary, databaseSummarySyncedAt: data.data.summarySyncedAt }; setSelected(next); setDatabaseSummary(data.data.summary); setTenants((items) => items.map((item) => item.id === tenant.id ? next : item)); if (!silent) setNotice(`Đã đồng bộ dung lượng database của ${tenant.domain}`) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể đồng bộ dung lượng database') } finally { setSummaryLoading(false) } }
  const syncAllDatabaseSummaries = async () => { setError(''); setAllSummariesLoading(true); try { const data = await call('/tenants/sync-database-summaries', { method: 'POST' }); await loadAll(); const failed = data.data.failed.length; setNotice(failed ? `Đã đồng bộ ${data.data.synced.length}/${data.data.total} tenant; ${failed} tenant chưa đồng bộ được` : `Đã đồng bộ dung lượng cho ${data.data.total} tenant`) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể đồng bộ danh sách database') } finally { setAllSummariesLoading(false) } }
  const runSeed = async (tenant: Tenant) => {
    if (!window.confirm(`Chạy lại seed dữ liệu mặc định cho ${tenant.domain}? Các dữ liệu đã có sẽ được giữ nguyên.`)) return
    setError('')
    setSeedLoading(true)
    try {
      await call(`/tenants/${tenant.id}/seed`, { method: 'POST' })
      setNotice(`Đã đồng bộ Backend và chạy seed cho ${tenant.domain}`)
      await openDetail(tenant)
    } catch (e) { setError(e instanceof Error ? e.message : 'Không thể chạy seed tenant') } finally { setSeedLoading(false) }
  }
  const toggleAdmin = async (admin: Admin) => { try { await call(`/admins/${admin.id}`, { method: 'PATCH', body: JSON.stringify({ isActive: !admin.isActive }) }); setNotice('Đã cập nhật Super Admin'); await loadAll() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật Super Admin') } }
  if (!token) return <main className="login"><form onSubmit={login}><h1>Tenant Console</h1><p>Đăng nhập Super Admin</p><label>Email<input name="email" type="email" defaultValue="superadmin@vienvu.com" required /></label><label>Mật khẩu<input name="password" type="password" required /></label>{error && <span className="error">{error}</span>}<button className="primary">Đăng nhập</button></form></main>
  const nav = (key: Screen, label: string) => <button className={screen === key ? 'nav-active' : ''} onClick={() => navigate(key)}>{label}</button>
  return <main className="console"><aside><div className="brand">TENANT<br /><strong>CONSOLE</strong></div><nav>{nav('dashboard', 'Tổng quan')}{nav('tenants', 'Tenant')}{nav('admins', 'Super Admin')}</nav><button className="logout" onClick={() => { void request('/auth/logout', { method: 'POST' }); setToken(null); router.push('/') }}>Đăng xuất</button></aside><section className="content">{error && <p className="message error">{error}</p>}{notice && <p className="message success">{notice}</p>}
    {screen === 'dashboard' && <><header><div><h1>Tổng quan nền tảng</h1><p>Trạng thái quản lý các hệ thống tenant.</p></div><button onClick={() => void loadAll()}>Làm mới</button></header><div className="metrics"><Metric label="Tổng tenant" value={dashboard?.totalTenants ?? '—'} /><Metric label="Đang hoạt động" value={dashboard?.activeTenants ?? '—'} good /><Metric label="Tạm dừng" value={dashboard?.inactiveTenants ?? '—'} /><Metric label="Super Admin" value={dashboard?.activeAdmins ?? '—'} /></div><section className="card"><h2>Tenant cập nhật gần đây</h2><TenantTable rows={dashboard?.latestTenants || []} onDetail={(id) => { const tenant = tenants.find((item) => item.id === id); if (tenant) void openDetail(tenant) }} /></section></>}
    {screen === 'tenants' && <><header><div><h1>Quản lý tenant</h1><p>Danh sách đọc dung lượng đã cache. Dùng nút đồng bộ khi cần làm mới tất cả.</p></div><div><button disabled={allSummariesLoading} onClick={() => void syncAllDatabaseSummaries()}>{allSummariesLoading ? 'Đang đồng bộ tất cả…' : 'Đồng bộ dung lượng tất cả'}</button><button className="primary" onClick={() => setEditing({ id: '', domain: '', databaseName: '', isActive: true })}>Thêm tenant</button></div></header>{editing && <section className="card"><h2>{editing.id ? 'Cập nhật tenant' : 'Thêm tenant'}</h2><form className="form-grid" onSubmit={saveTenant}><fieldset disabled={tenantSaving}><label>Domain<input name="domain" defaultValue={editing.domain} required placeholder="clinic-a.example.com" /></label><label>Tên database<input name="databaseName" defaultValue={editing.databaseName} required placeholder="erp_dev6" pattern="[A-Za-z0-9_-]{1,64}" /><small>Nhập nguyên tên database cần tạo, ví dụ: <code>erp_dev6</code>.</small></label>{!editing.id && <label>Clone từ tenant mẫu<select name="cloneFromTenantId" defaultValue=""><option value="">Không clone — tạo dữ liệu mặc định</option>{tenants.filter((tenant) => tenant.isActive).map((tenant) => <option key={tenant.id} value={tenant.id}>{tenant.domain} ({tenant.databaseName})</option>)}</select><small>Clone sao chép toàn bộ bảng và dữ liệu từ tenant mẫu vào database mới.</small></label>}<label className="check"><input name="isActive" type="checkbox" defaultChecked={editing.isActive} /> Đang hoạt động</label><div className="form-actions"><button className="primary">{tenantSaving ? 'Đang tạo / sao chép dữ liệu…' : 'Lưu tenant'}</button><button type="button" onClick={() => setEditing(null)}>Huỷ</button></div></fieldset>{tenantSaving && <p className="form-progress">Đang tạo database và đồng bộ dữ liệu. Không đóng trang này.</p>}</form></section>}<section className="card"><TenantTable rows={tenants} onDetail={(id) => { const tenant = tenants.find((item) => item.id === id); if (tenant) void openDetail(tenant) }} onEdit={(id) => setEditing(tenants.find((item) => item.id === id) || null)} /></section></>}
    {screen === 'admins' && <><header><div><h1>Quản lý Super Admin</h1><p>Tài khoản quản trị management database, tách biệt hoàn toàn tenant.</p></div></header><div className="two-column"><section className="card"><h2>Thêm Super Admin</h2><form className="form-grid" onSubmit={saveAdmin}><label>Họ tên<input name="fullName" required /></label><label>Email<input name="email" type="email" required /></label><label>Mật khẩu<input name="password" type="password" minLength={12} required /></label><button className="primary">Tạo tài khoản</button></form></section><section className="card"><h2>Danh sách tài khoản</h2>{admins.map((admin) => <div className="admin-row" key={admin.id}><span><strong>{admin.fullName}</strong><small>{admin.email}</small></span><span><span className={admin.isActive ? 'badge good' : 'badge'}>{admin.isActive ? 'Hoạt động' : 'Tạm dừng'}</span><button onClick={() => void toggleAdmin(admin)}>{admin.isActive ? 'Tạm dừng' : 'Kích hoạt'}</button></span></div>)}</section></div></>}
    {screen === 'detail' && !selected && <p className="message loading">Đang tải thông tin tenant…</p>}
    {screen === 'detail' && selected && <><header><div><button onClick={() => navigate('tenants')}>← Tenant</button><h1>{selected.domain}</h1><p>{summaryLoading ? 'Đang đồng bộ số liệu database…' : 'Trang chi tiết và giám sát tenant.'}</p></div><div><button className="primary" disabled={!selected.isActive || seedLoading} onClick={() => void runSeed(selected)}>{seedLoading ? 'Đang đồng bộ & seed…' : 'Đồng bộ & Seed'}</button><button disabled={seedLoading || summaryLoading} onClick={() => void openDetail(selected, false)}>Kiểm tra lại</button></div></header>{seedLoading && <p className="message loading">Đang đồng bộ tenant với Backend và khởi tạo dữ liệu mặc định. Vui lòng chờ.</p>}<div className="metrics"><Metric label="Trạng thái tenant" value={selected.isActive ? 'Hoạt động' : 'Tạm dừng'} good={selected.isActive} /><Metric label="Database" value={monitor?.status === 'healthy' ? 'Kết nối tốt' : monitor?.status === 'unreachable' ? 'Không kết nối' : 'Đang kiểm tra'} good={monitor?.status === 'healthy'} /><Metric label="Độ trễ DB" value={monitor ? `${monitor.latencyMs} ms` : '—'} /><Metric label="Dung lượng DB" value={databaseSummary ? formatBytes(databaseSummary.sizeBytes) : '—'} /><Metric label="Số bảng" value={databaseSummary?.totalTables ?? '—'} /><Metric label="Dòng ước tính" value={databaseSummary ? databaseSummary.estimatedRows.toLocaleString('vi-VN') : '—'} /></div><section className="card detail-grid"><div><span>Domain</span><strong>{selected.domain}</strong></div><div><span>Tên database</span><strong>{selected.databaseName}</strong></div><div><span>Database engine</span><strong>{databaseSummary?.engine || '—'}</strong></div><div><span>Đồng bộ dung lượng</span><strong>{selected.databaseSummarySyncedAt ? new Date(selected.databaseSummarySyncedAt).toLocaleString('vi-VN') : 'Chưa đồng bộ'}</strong></div></section>{databaseSummary && <section className="card tenant-table-summary"><h2>Top bảng theo dung lượng</h2><table><thead><tr><th>Bảng</th><th>Số dòng (ước tính)</th><th>Dung lượng</th></tr></thead><tbody>{databaseSummary.largestTables.map((table) => <tr key={table.name}><td>{table.name}</td><td>{table.rows.toLocaleString('vi-VN')}</td><td>{formatBytes(table.sizeBytes)}</td></tr>)}</tbody><tfoot><tr><th>Tổng</th><th>{databaseSummary.estimatedRows.toLocaleString('vi-VN')}</th><th>{formatBytes(databaseSummary.sizeBytes)}</th></tr></tfoot></table><small>Phiên bản DB: {databaseSummary.version}</small></section>}</>}
  </section></main>
}
function Metric({ label, value, good }: { label: string; value: string | number; good?: boolean }) { return <div className="metric"><span>{label}</span><strong className={good ? 'good-text' : ''}>{value}</strong></div> }
function formatBytes(value: number) { if (!value) return '0 B'; const units = ['B', 'KB', 'MB', 'GB', 'TB']; const index = Math.min(units.length - 1, Math.floor(Math.log(value) / Math.log(1024))); return `${(value / (1024 ** index)).toFixed(index < 2 ? 0 : 2)} ${units[index]}` }
function TenantTable({ rows, onDetail, onEdit }: { rows: Array<Pick<Tenant, 'id' | 'domain' | 'isActive' | 'updatedAt' | 'databaseSummary' | 'databaseSummarySyncedAt'>>; onDetail: (id: string) => void; onEdit?: (id: string) => void }) { return <table><thead><tr><th>Domain</th><th>Trạng thái</th><th>Dung lượng DB</th><th>Đồng bộ</th><th>Cập nhật</th><th /></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><button className="link" onClick={() => onDetail(item.id)}>{item.domain}</button></td><td><span className={item.isActive ? 'badge good' : 'badge'}>{item.isActive ? 'Hoạt động' : 'Tạm dừng'}</span></td><td>{item.databaseSummary ? formatBytes(item.databaseSummary.sizeBytes) : '—'}</td><td>{item.databaseSummarySyncedAt ? new Date(item.databaseSummarySyncedAt).toLocaleString('vi-VN') : 'Chưa đồng bộ'}</td><td>{item.updatedAt ? new Date(item.updatedAt).toLocaleDateString('vi-VN') : '—'}</td><td>{onEdit && <button onClick={() => onEdit(item.id)}>Sửa</button>}</td></tr>)}</tbody></table> }
