'use client'
import { FormEvent, useEffect, useState } from 'react'

type Tenant = { id: string; domain: string; databaseUrl: string; isActive: boolean; updatedAt?: string }
type Admin = { id: string; email: string; fullName: string; isActive: boolean; createdAt?: string }
type Dashboard = { totalTenants: number; activeTenants: number; inactiveTenants: number; activeAdmins: number; latestTenants: Array<Pick<Tenant, 'id' | 'domain' | 'isActive' | 'updatedAt'>> }
type Screen = 'dashboard' | 'tenants' | 'admins' | 'detail'
const request = async (path: string, token?: string, init?: RequestInit) => fetch(`/api${path}`, { ...init, headers: { 'Content-Type': 'application/json', ...(token ? { Authorization: `Bearer ${token}` } : {}), ...init?.headers } })

export default function Home() {
  const [token, setToken] = useState<string | null>(null), [screen, setScreen] = useState<Screen>('dashboard'), [tenants, setTenants] = useState<Tenant[]>([]), [admins, setAdmins] = useState<Admin[]>([]), [dashboard, setDashboard] = useState<Dashboard | null>(null), [selected, setSelected] = useState<Tenant | null>(null), [editing, setEditing] = useState<Tenant | null>(null), [error, setError] = useState(''), [notice, setNotice] = useState(''), [monitor, setMonitor] = useState<{ status: string; latencyMs: number } | null>(null)
  const call = async (path: string, init?: RequestInit) => { const res = await request(path, token || undefined, init); if (res.status === 401) { localStorage.removeItem('tenant-console-token'); setToken(null); throw new Error('Phiên đăng nhập đã hết hạn') } const data = await res.json(); if (!res.ok) throw new Error(data.message || 'Không thể thực hiện yêu cầu'); return data }
  const loadAll = async (activeToken = token) => { if (!activeToken) return; try { const load = async (path: string) => { const response = await request(path, activeToken); const data = await response.json(); if (!response.ok) throw new Error(data.message || 'Không thể tải dữ liệu'); return data }; const [dashboardData, tenantData, adminData] = await Promise.all([load('/dashboard'), load('/tenants'), load('/admins')]); setDashboard(dashboardData.data); setTenants(tenantData.data); setAdmins(adminData.data) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tải dữ liệu') } }
  useEffect(() => { const stored = localStorage.getItem('tenant-console-token'); setToken(stored); if (stored) void loadAll(stored) }, [])
  const login = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(''); const fd = new FormData(event.currentTarget); const res = await request('/auth/login', undefined, { method: 'POST', body: JSON.stringify({ email: fd.get('email'), password: fd.get('password') }) }); const data = await res.json(); if (!res.ok) { setError(data.message || 'Thông tin đăng nhập không đúng'); return } localStorage.setItem('tenant-console-token', data.accessToken); setToken(data.accessToken); setTimeout(() => void loadAll(), 0) }
  const saveTenant = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); try { await call(editing ? `/tenants/${editing.id}` : '/tenants', { method: editing ? 'PATCH' : 'POST', body: JSON.stringify({ domain: fd.get('domain'), databaseUrl: fd.get('databaseUrl'), isActive: fd.get('isActive') === 'on' }) }); setNotice('Đã lưu tenant'); setEditing(null); await loadAll() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể lưu tenant') } }
  const saveAdmin = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); const fd = new FormData(event.currentTarget); try { await call('/admins', { method: 'POST', body: JSON.stringify({ fullName: fd.get('fullName'), email: fd.get('email'), password: fd.get('password') }) }); setNotice('Đã tạo Super Admin'); event.currentTarget.reset(); await loadAll() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể tạo Super Admin') } }
  const openDetail = async (tenant: Tenant) => { setSelected(tenant); setScreen('detail'); setMonitor(null); try { const data = await call(`/tenants/${tenant.id}/monitor`); setMonitor(data.data.database) } catch (e) { setError(e instanceof Error ? e.message : 'Không thể kiểm tra tenant') } }
  const toggleAdmin = async (admin: Admin) => { try { await call(`/admins/${admin.id}`, { method: 'PATCH', body: JSON.stringify({ isActive: !admin.isActive }) }); setNotice('Đã cập nhật Super Admin'); await loadAll() } catch (e) { setError(e instanceof Error ? e.message : 'Không thể cập nhật Super Admin') } }
  if (!token) return <main className="login"><form onSubmit={login}><h1>Tenant Console</h1><p>Đăng nhập Super Admin</p><label>Email<input name="email" type="email" required /></label><label>Mật khẩu<input name="password" type="password" required /></label>{error && <span className="error">{error}</span>}<button className="primary">Đăng nhập</button></form></main>
  const nav = (key: Screen, label: string) => <button className={screen === key ? 'nav-active' : ''} onClick={() => setScreen(key)}>{label}</button>
  return <main className="console"><aside><div className="brand">TENANT<br /><strong>CONSOLE</strong></div><nav>{nav('dashboard', 'Tổng quan')}{nav('tenants', 'Tenant')}{nav('admins', 'Super Admin')}</nav><button className="logout" onClick={() => { localStorage.removeItem('tenant-console-token'); setToken(null) }}>Đăng xuất</button></aside><section className="content">{error && <p className="message error">{error}</p>}{notice && <p className="message success">{notice}</p>}
    {screen === 'dashboard' && <><header><div><h1>Tổng quan nền tảng</h1><p>Trạng thái quản lý các hệ thống tenant.</p></div><button onClick={() => void loadAll()}>Làm mới</button></header><div className="metrics"><Metric label="Tổng tenant" value={dashboard?.totalTenants ?? '—'} /><Metric label="Đang hoạt động" value={dashboard?.activeTenants ?? '—'} good /><Metric label="Tạm dừng" value={dashboard?.inactiveTenants ?? '—'} /><Metric label="Super Admin" value={dashboard?.activeAdmins ?? '—'} /></div><section className="card"><h2>Tenant cập nhật gần đây</h2><TenantTable rows={dashboard?.latestTenants || []} onDetail={(id) => { const tenant = tenants.find((item) => item.id === id); if (tenant) void openDetail(tenant) }} /></section></>}
    {screen === 'tenants' && <><header><div><h1>Quản lý tenant</h1><p>Domain và database URL chỉ hiển thị trên Tenant Console.</p></div><button className="primary" onClick={() => setEditing({ id: '', domain: '', databaseUrl: '', isActive: true })}>Thêm tenant</button></header>{editing && <section className="card"><h2>{editing.id ? 'Cập nhật tenant' : 'Thêm tenant'}</h2><form className="form-grid" onSubmit={saveTenant}><label>Domain<input name="domain" defaultValue={editing.domain} required placeholder="clinic-a.example.com" /></label><label>Database URL<input name="databaseUrl" defaultValue={editing.databaseUrl} required placeholder="mysql://user:password@host:3306/db" /></label><label className="check"><input name="isActive" type="checkbox" defaultChecked={editing.isActive} /> Đang hoạt động</label><div><button className="primary">Lưu</button><button type="button" onClick={() => setEditing(null)}>Huỷ</button></div></form></section>}<section className="card"><TenantTable rows={tenants} onDetail={(id) => { const tenant = tenants.find((item) => item.id === id); if (tenant) void openDetail(tenant) }} onEdit={(id) => setEditing(tenants.find((item) => item.id === id) || null)} /></section></>}
    {screen === 'admins' && <><header><div><h1>Quản lý Super Admin</h1><p>Tài khoản quản trị management database, tách biệt hoàn toàn tenant.</p></div></header><div className="two-column"><section className="card"><h2>Thêm Super Admin</h2><form className="form-grid" onSubmit={saveAdmin}><label>Họ tên<input name="fullName" required /></label><label>Email<input name="email" type="email" required /></label><label>Mật khẩu<input name="password" type="password" minLength={12} required /></label><button className="primary">Tạo tài khoản</button></form></section><section className="card"><h2>Danh sách tài khoản</h2>{admins.map((admin) => <div className="admin-row" key={admin.id}><span><strong>{admin.fullName}</strong><small>{admin.email}</small></span><span><span className={admin.isActive ? 'badge good' : 'badge'}>{admin.isActive ? 'Hoạt động' : 'Tạm dừng'}</span><button onClick={() => void toggleAdmin(admin)}>{admin.isActive ? 'Tạm dừng' : 'Kích hoạt'}</button></span></div>)}</section></div></>}
    {screen === 'detail' && selected && <><header><div><button onClick={() => setScreen('tenants')}>← Tenant</button><h1>{selected.domain}</h1><p>Trang chi tiết và giám sát tenant.</p></div><button onClick={() => void openDetail(selected)}>Kiểm tra lại</button></header><div className="metrics"><Metric label="Trạng thái tenant" value={selected.isActive ? 'Hoạt động' : 'Tạm dừng'} good={selected.isActive} /><Metric label="Database" value={monitor?.status === 'healthy' ? 'Kết nối tốt' : monitor?.status === 'unreachable' ? 'Không kết nối' : 'Đang kiểm tra'} good={monitor?.status === 'healthy'} /><Metric label="Độ trễ DB" value={monitor ? `${monitor.latencyMs} ms` : '—'} /></div><section className="card detail-grid"><div><span>Domain</span><strong>{selected.domain}</strong></div><div><span>Database URL</span><code>{selected.databaseUrl}</code></div><div><span>Đồng bộ gần nhất</span><strong>{selected.updatedAt ? new Date(selected.updatedAt).toLocaleString('vi-VN') : '—'}</strong></div></section></>}
  </section></main>
}
function Metric({ label, value, good }: { label: string; value: string | number; good?: boolean }) { return <div className="metric"><span>{label}</span><strong className={good ? 'good-text' : ''}>{value}</strong></div> }
function TenantTable({ rows, onDetail, onEdit }: { rows: Array<Pick<Tenant, 'id' | 'domain' | 'isActive' | 'updatedAt'>>; onDetail: (id: string) => void; onEdit?: (id: string) => void }) { return <table><thead><tr><th>Domain</th><th>Trạng thái</th><th>Cập nhật</th><th /></tr></thead><tbody>{rows.map((item) => <tr key={item.id}><td><button className="link" onClick={() => onDetail(item.id)}>{item.domain}</button></td><td><span className={item.isActive ? 'badge good' : 'badge'}>{item.isActive ? 'Hoạt động' : 'Tạm dừng'}</span></td><td>{item.updatedAt ? new Date(item.updatedAt).toLocaleDateString('vi-VN') : '—'}</td><td>{onEdit && <button onClick={() => onEdit(item.id)}>Sửa</button>}</td></tr>)}</tbody></table> }
