import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
  Appointment,
  AuditLog,
  BranchRoleAssignment,
  Branch,
  Commission,
  Consultation,
  CustomFieldDefinition,
  CustomFieldValue,
  CustomerImage,
  Customer,
  Department,
  DynamicRoleDefinition,
  Expense,
  FileFolder,
  ManagedFile,
  Invoice,
  Lead,
  LeadActivity,
  MedicalEpisode,
  Product,
  ServiceOrder,
  Staff,
  StockBatch,
  Supplier,
  Treatment,
  User,
  ViewSetting,
  WorkSchedule,
} from '../entities/entities';
import { RecordsController } from './records.controller';
import { RecordsService } from './records.service';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Branch,
      Department,
      Staff,
      BranchRoleAssignment,
      User,
      DynamicRoleDefinition,
      Customer,
      Lead,
      LeadActivity,
      Supplier,
      Product,
      MedicalEpisode,
      Appointment,
      WorkSchedule,
      StockBatch,
      Consultation,
      ServiceOrder,
      CustomerImage,
      FileFolder,
      ManagedFile,
      Invoice,
      Expense,
      Treatment,
      Commission,
      CustomFieldDefinition,
      CustomFieldValue,
      ViewSetting,
      AuditLog,
    ]),
  ],
  controllers: [RecordsController],
  providers: [RecordsService],
  exports: [RecordsService],
})
export class RecordsModule {}
