import { Module } from '@nestjs/common';
import { TenantOrmModule } from '../tenant/tenant-orm.module';
import {
  Appointment,
  AccountingCashFlowMapping,
  AccountingChartAccount,
  AccountingFiscalSetting,
  AccountingPeriod,
  AccountingVoucher,
  AccountingVoucherLine,
  Attendance,
  AttendanceAdjustmentRequest,
  AuditLog,
  BranchRoleAssignment,
  Branch,
  BusinessTripRequest,
  Commission,
  Consultation,
  ContentNews,
  ContentPost,
  CustomFieldDefinition,
  CustomFieldValue,
  CustomTableRow,
  CustomerImage,
  Customer,
  Department,
  DynamicRoleDefinition,
  Equipment,
  Expense,
  FileFolder,
  ManagedFile,
  Invoice,
  Lead,
  LeadActivity,
  LeaveRequest,
  MedicalEpisode,
  Payroll,
  PaymentRequest,
  PerformanceReview,
  PositionHistory,
  RecordDraft,
  Product,
  Unit,
  Room,
  ServiceOrder,
  ServiceOrderItem,
  Staff,
  StaffInsurance,
  StaffReward,
  StaffTraining,
  StockBatch,
  Supplier,
  Treatment,
  User,
  ViewSetting,
  WorkContract,
  WorkflowAction,
  WorkflowDefinition,
  WorkflowInstance,
  WorkflowStep,
  WorkflowTask,
  WorkSchedule,
} from '../entities/entities';
import { RecordsController } from './records.controller';
import { RecordsService } from './records.service';
import { WorkflowModule } from '../workflow/workflow.module';

@Module({
  imports: [
    WorkflowModule,
    TenantOrmModule.forFeature([
      Branch,
      Department,
      Room,
      Equipment,
      Staff,
      BranchRoleAssignment,
      User,
      DynamicRoleDefinition,
      Customer,
      Lead,
      LeadActivity,
      Supplier,
      Product,
      Unit,
      MedicalEpisode,
      Appointment,
      AccountingPeriod,
      AccountingChartAccount,
      AccountingFiscalSetting,
      AccountingCashFlowMapping,
      AccountingVoucher,
      AccountingVoucherLine,
      WorkSchedule,
      StockBatch,
      Consultation,
      ServiceOrder,
      ServiceOrderItem,
      CustomerImage,
      FileFolder,
      ManagedFile,
      Invoice,
      Expense,
      Treatment,
      Commission,
      ContentPost,
      ContentNews,
      CustomFieldDefinition,
      CustomFieldValue,
      CustomTableRow,
      ViewSetting,
      AuditLog,
      WorkContract,
      StaffInsurance,
      Attendance,
      AttendanceAdjustmentRequest,
      LeaveRequest,
      BusinessTripRequest,
      PaymentRequest,
      WorkflowDefinition,
      WorkflowStep,
      WorkflowInstance,
      WorkflowTask,
      WorkflowAction,
      Payroll,
      StaffReward,
      StaffTraining,
      PerformanceReview,
      PositionHistory,
      RecordDraft,
    ]),
  ],
  controllers: [RecordsController],
  providers: [RecordsService],
  exports: [RecordsService],
})
export class RecordsModule {}
