import { Module } from '@nestjs/common';
import { TypeOrmModule } from '@nestjs/typeorm';
import {
  Appointment,
  Attendance,
  AuditLog,
  BranchRoleAssignment,
  Branch,
  Commission,
  Consultation,
  CustomFieldDefinition,
  CustomFieldValue,
  CustomerImage,
  Customer,
  Department,
  DynamicRoleDefinition,
  Equipment,
  Expense,
  FileFolder,
  ManagedFile,
  Invoice,
  Lead,
  LeadActivity,
  LeaveRequest,
  MedicalEpisode,
  Payroll,
  PerformanceReview,
  PositionHistory,
  Product,
  Room,
  ServiceOrder,
  ServiceOrderItem,
  Staff,
  StaffInsurance,
  StaffReward,
  StaffTraining,
  StockBatch,
  Supplier,
  Treatment,
  User,
  ViewSetting,
  WorkContract,
  WorkSchedule,
} from '../entities/entities';
import { RecordsController } from './records.controller';
import { RecordsService } from './records.service';

@Module({
  imports: [
    TypeOrmModule.forFeature([
      Branch,
      Department,
      Room,
      Equipment,
      Staff,
      BranchRoleAssignment,
      User,
      DynamicRoleDefinition,
      Customer,
      Lead,
      LeadActivity,
      Supplier,
      Product,
      MedicalEpisode,
      Appointment,
      WorkSchedule,
      StockBatch,
      Consultation,
      ServiceOrder,
      ServiceOrderItem,
      CustomerImage,
      FileFolder,
      ManagedFile,
      Invoice,
      Expense,
      Treatment,
      Commission,
      CustomFieldDefinition,
      CustomFieldValue,
      ViewSetting,
      AuditLog,
      WorkContract,
      StaffInsurance,
      Attendance,
      LeaveRequest,
      Payroll,
      StaffReward,
      StaffTraining,
      PerformanceReview,
      PositionHistory,
    ]),
  ],
  controllers: [RecordsController],
  providers: [RecordsService],
  exports: [RecordsService],
})
export class RecordsModule {}
