/// Generated by build.sh. Do not edit manually.
class BuildEnvironment {
  BuildEnvironment._();
  static const name = 'dev';
  static const apiBaseUrl = 'http://localhost:9998/api';
  static const tenantDomain = 'dev5.vienvu.com';
}
