#!/usr/bin/env bash
set -euo pipefail

# Usage: ./build.sh <dev|lea|prod> [apk|appbundle|ios]
ENVIRONMENT="${1:-dev}"
TARGET="${2:-}"

case "$ENVIRONMENT" in
  dev)  API_URL='http://localhost:9998/api'; DOMAIN='dev5.vienvu.com'; BUNDLE='com.vienvu.customerapp.dev'; NAME='Customer Dev' ;;
  lea)  API_URL='https://lea.vienvu.com/api'; DOMAIN='lea.vienvu.com'; BUNDLE='com.vienvu.customerapp.lea'; NAME='Customer LEA' ;;
  prod) API_URL='https://api.vienvu.com/api'; DOMAIN='vienvu.com'; BUNDLE='com.vienvu.customerapp'; NAME='Customer' ;;
  *) echo 'Usage: ./build.sh <dev|lea|prod> [apk|appbundle|ios]'; exit 64 ;;
esac

cat > lib/core/api/build_environment.dart <<EOF
/// Generated by build.sh. Do not edit manually.
class BuildEnvironment {
  BuildEnvironment._();
  static const name = '$ENVIRONMENT';
  static const apiBaseUrl = '$API_URL';
  static const tenantDomain = '$DOMAIN';
}
EOF

python3 - "$BUNDLE" "$NAME" <<'PY'
from pathlib import Path
import re, sys
bundle, name = sys.argv[1:]
android = Path('android/app/build.gradle.kts')
text = android.read_text()
text = re.sub(r'namespace\s*=\s*"[^"]+"', f'namespace = "{bundle}"', text)
text = re.sub(r'applicationId\s*=\s*"[^"]+"', f'applicationId = "{bundle}"', text)
android.write_text(text)
project = Path('ios/Runner.xcodeproj/project.pbxproj')
text = project.read_text()
text = re.sub(r'(PRODUCT_BUNDLE_IDENTIFIER = )(?![^;]*RunnerTests;)[^;]+;', lambda m: f'{m.group(1)}{bundle};', text)
project.write_text(text)
plist = Path('ios/Runner/Info.plist')
text = plist.read_text()
plist.write_text(re.sub(r'(<key>CFBundleDisplayName</key>\s*<string>).*?(</string>)', rf'\g<1>{name}\2', text, flags=re.S))
PY

echo "Configured $ENVIRONMENT: $DOMAIN → $API_URL ($BUNDLE)"
case "$TARGET" in
  '') ;;
  apk) flutter build apk --dart-define=API_BASE_URL="$API_URL" --dart-define=TENANT_DOMAIN="$DOMAIN" ;;
  appbundle) flutter build appbundle --dart-define=API_BASE_URL="$API_URL" --dart-define=TENANT_DOMAIN="$DOMAIN" ;;
  ios) flutter build ipa --dart-define=API_BASE_URL="$API_URL" --dart-define=TENANT_DOMAIN="$DOMAIN" ;;
  *) echo 'Target: apk, appbundle, ios'; exit 64 ;;
esac
